# -*- coding: utf-8 -*-
"""Copy of Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PW4bTsyzKY275TBN4-ZQf_cbTNrK2dvj
"""

# IMPLEMENT YOUR FUNCTIONS IN THIS CODE CELL OR
# IN THE PREVIOUS CODE CELL(S) THAT YOU MAY WANT TO CREATE
def import_inventory():
  f = open("products.txt", encoding="latin-1")
  d = {}
  for line in f:
    line = line.lower().strip().split("-")
    for kalas in line:
      kalas=kalas.split("_")
      if kalas[0] not in d :  
        d[kalas[0]] = int(kalas[1])
      else:
        d[kalas[0]]+= int(kalas[1]) 
  f.close()
  kasa = {}
  kedi = sorted(d.keys())

  for makine in kedi:
    kasa[makine] = int(d[makine])
  return kasa
def show_remaining(products):
  for galicya in products:
    print(galicya,":",products[galicya])
  if products == {} : 
    print("Inventory is empty!")
def sell_product(products):
  decision = input("Please enter products to sell: ")
  decision = decision.lower().split("-")
  for rwanda in decision:
    rwanda = rwanda.split("_")
    if rwanda[0] in products:
      if int(rwanda[1]) > int(products[rwanda[0]]) :
        print("There is not enough",rwanda[0],"in inventory.")
      elif int(rwanda[1]) == int(products[rwanda[0]]):
        products.pop(rwanda[0])
        print(rwanda[1],rwanda[0], "sold.")

      elif int(rwanda[1]) < int(products[rwanda[0]]) :
        print(rwanda[1],rwanda[0], "sold.")
        products[rwanda[0]] -= int(rwanda[1])

    else:
      print(rwanda[0],"does not exist in inventory.")

# DO NOT MODIFY THIS CODE CELL, JUST RUN IT

products = import_inventory()
decision = ""
while decision != "3":
  print("*---------------------------")
  print("[1] Sell products")
  print("[2] Show remaining inventory")
  print("[3] Terminate")

  decision = input("Please enter your decision: ")
  print("____________________________")
  if decision == "1":
    sell_product(products)
  elif decision == "2":
    show_remaining(products)
  elif decision == "3":
    print("Terminating...")
  else:
    print("Invalid input!")